version: '3.8'
services:
  api:
    build: .
    ports:
      - '8888:8888'
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=vmytest
    volumes:
      - data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
volumes:
  data:
networks:
  host: