version: '3.8'
services:
  api:
    build: .
    ports:
      - '8888:8888'
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
volumes:
  data:
networks:
  host: